addSbtPlugin("org.scoverage"             % "sbt-coveralls"  % "1.3.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"   % "2.4.3")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"  % "1.9.3")
addSbtPlugin("com.typesafe.sbt"          % "sbt-site"       % "1.3.3")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.1.13")
addSbtPlugin("com.codecommit" % "sbt-github-packages" % "0.5.3")
