name: RELEASE

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: coursier/cache-action@v6
    - name: Deploy snowplow-maxmind-iplookups to Github Packages
      run: sbt publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
